# -*- coding: utf-8 -*-
"""課題_クラスを使いこなそう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgwKBRqwhwJOycZoK9AgT5uNumLAkiUM
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def printinfo(self):
        print("名前：", self.name)
        print("年齢：", self.age)

human = Human("侍太郎", 20)

human.printinfo()