# -*- coding: utf-8 -*-
"""課題_関数を使いこなそう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMnRvSoVou2n8kS16R3AUFTGzSVXUHoP
"""

def add_two_arguments(price, tax):

    tax_amount = price * (tax / 100)
    total_price = price + tax_amount
    print(f"{price}円（税込：{total_price}円）")

add_two_arguments(1200, 10)