# -*- coding: utf-8 -*-
"""課題_関数を使いこなそう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMnRvSoVou2n8kS16R3AUFTGzSVXUHoP
"""

def tortal_price(price, tax):
      return price + price * (tax / 100)

x = tortal_price(1200, 10)
print("税込：", x ,"円")