# -*- coding: utf-8 -*-
"""課題_変数を使って四則演算しよう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1JDcYnI1QxvVptRA6PueHQY9eYDyy2j
"""

top_side = 10
bottom_side = 20
hight = 5

print(f"{(top_side + bottom_side) * hight / 2}cm²")