# -*- coding: utf-8 -*-
"""課題_変数スコープを正しく使おう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_08dh-sUfP_rHDdW3iQCOecH5eF0tuIO
"""

price1 = 100
price2 = 200
tax = 1.1

def total():
    return price1 + price2

print (total() * tax)