# -*- coding: utf-8 -*-
"""課題_学習したことを組み合わせてコードを書こう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rjTn_JeFZ0fCDN8iEywHIpQuSHMcChrK
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def check_adult(self):
        if self.age >= 20:
          print(f"{self.name}は大人です。")

        else:
          print(f"{self.name}は大人ではありません。")

human1 = Human("一郎", 10)
human2 = Human("花子", 14)
human3 = Human("二郎", 20)
human4 = Human("知子", 25)
human5 = Human("三郎", 36)

human_list = [human1, human2, human3, human4, human5]

for human in human_list:
    human.check_adult()