# -*- coding: utf-8 -*-
"""課題_繰り返し処理を使いこなそう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqS4VzZBOUAGdU_P9h-npUYpwrKs9VDA
"""

list = ["水", "金", "地", "火", "木", "土", "天", "海", "冥"]

for value in list:
    print(value)


list_length = len(list)

index = 0

while index < len(list):
      if index == len(list):
         break

      print(list[index])
      index += 1